---
- name: A simple playbook to test ansible.cfg
  hosts: renamed:!taz
  gather_facts: no

  tasks:

  # the command module issues a command on the remote host
  - name: Issue a date cmd on each remote host
    command: date
